version: '3.8'

services:
  app:
    build: .
    container_name: text-enhancer-assistant
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./documentation.md:/app/documentation.md
      - ./.env:/app/.env
    environment:
      - TZ=Europe/Moscow
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 